name: 'C-Chain Re-Execution Benchmark'
description: 'Run C-Chain re-execution benchmark'

inputs:
  task:
    description: 'Task name to execute from Taskfile.yml. Leave empty to use custom inputs below.'
    default: ''

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: 'container build test' 
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install Task
          uses: go-task/setup-task@v1
          with:
             version: 3.x # Use a specific version or range

        - name: Run build task
          run: task build # Executes the 'build' task defined in your Taskfile
